#!/usr/bin/env bash
#
# Verify the GitHub Pages custom domain (swmm6.is-local.org).
# Walks you through: add the domain in GitHub profile settings, add the TXT
# challenge record at open-domains.com, confirm DNS propagation, finish Verify.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE="${ENV_FILE:-.custom-domain.env}"

# Config (override via env if the domain or GitHub user changes).
DOMAIN="${DOMAIN:-swmm6.is-local.org}"
GH_USER="${GH_USER:-JoaquinAlvarado-py}"
CHALLENGE_NAME="_github-pages-challenge-${GH_USER}"
CHALLENGE_FQDN="${CHALLENGE_NAME}.${DOMAIN}"

banner "Verify custom domain — ${DOMAIN}"

# check_txt — true if the challenge TXT record carries our token.
check_txt() {
  command -v dig >/dev/null 2>&1 || { warn "dig not available — check the record manually in your DNS provider"; return 1; }
  dig +short TXT "$CHALLENGE_FQDN" 2>/dev/null | grep -Fq "$CHALLENGE_TOKEN"
}

# txt_now — first value currently published for the challenge record (unquoted).
txt_now() {
  command -v dig >/dev/null 2>&1 || return 0
  dig +short TXT "$CHALLENGE_FQDN" 2>/dev/null | head -n1 | tr -d '"'
}

# ── Stage 1: add the domain in GitHub profile settings ─────────────────────
stage "GitHub — add the domain"
say "Verification lives in your PROFILE settings (not the repo)."
open_url "https://github.com/settings/pages"
step "Left sidebar → 'Code, planning, and automation' → Pages."
step "If '${DOMAIN}' already appears under 'Verified domains' (pending), skip ahead to copying the token it shows."
step "Otherwise click 'Add a domain', enter ${DOMAIN}, and click 'Add domain'."
pause "Done? GitHub now shows a 'Add a DNS TXT record' box (or you're on the pending entry)."
ask CHALLENGE_TOKEN "Paste the TXT record VALUE (the random token) GitHub displayed:"
write_env CHALLENGE_TOKEN "$CHALLENGE_TOKEN"
note "Record name GitHub wants: ${CHALLENGE_FQDN}"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 2: add the TXT record at open-domains.com ────────────────────────
stage "open-domains.com — TXT record"
say "is-local.org is run by Open Domains (moved off GitHub PRs to their platform)."
warn "Put the TOKEN in the value field — not the record name. Swapping them is the #1 cause of verification failures."
open_url "https://open-domains.com/login"
step "Log in with the account that owns the ${DOMAIN} subdomain."
step "Open DNS management for ${DOMAIN} (look for 'My subdomains' / DNS records / edit)."
step "If a TXT record named '${CHALLENGE_NAME}' already exists, EDIT it; otherwise ADD a new TXT record:"
say "    name (host):    ${CHALLENGE_NAME}"
say "    value (content): ${CHALLENGE_TOKEN}"
say "    TTL:            default"
step "Save. The 'name' is the part before '.${DOMAIN}' — it must NOT include the token."
note "Reference: https://open-domains.com/guides/dns-record-types/txt-record"
pause "Saved? Let's verify DNS."
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 3: confirm DNS propagation ───────────────────────────────────────
stage "Confirm DNS propagation"
say "Checking: dig TXT ${CHALLENGE_FQDN}"
if [[ -n "${CHALLENGE_TOKEN:-}" ]] && check_txt; then
  say "✓ TXT record found with the right value."
else
  now=$(txt_now)
  if [[ -n "$now" ]]; then
    warn "Record EXISTS but its value does not match the token:"
    say "    published: $now"
    say "    expected:  ${CHALLENGE_TOKEN}"
    say "Fix it: edit ${CHALLENGE_NAME} at open-domains.com and put the exact token in the VALUE field."
    if confirm "Re-check after ~30s?"; then
      for i in 1 2 3 4; do sleep 30; check_txt && break || true; done
      check_txt && say "✓ TXT record now matches." || warn "Still mismatched — confirm you saved the edited value."
    fi
  else
    warn "No TXT record found yet — DNS changes can take up to 24h."
    if command -v dig >/dev/null 2>&1; then
      if confirm "Re-check after ~30s?"; then
        for i in 1 2 3 4; do sleep 30; check_txt && break || true; done
        check_txt && say "✓ TXT record found now." || warn "Still not visible. Wait longer and re-run."
      fi
    fi
  fi
fi
pause "Continue to finish verification?"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 4: complete verification on GitHub ───────────────────────────────
stage "GitHub — complete the verification"
open_url "https://github.com/settings/pages"
step "Under 'Verified domains', find ${DOMAIN}."
step "Click the kebab menu (⋯) to its right → 'Continue verifying'."
step "Click 'Verify'."
pause "Clicked Verify?"
if confirm "Does ${DOMAIN} now show the 'Verified' badge?"; then
  say "✓ ${DOMAIN} is verified and protected against takeover."
else
  warn "Not verified yet — double-check the TXT value matches exactly (case-sensitive) and that it has propagated:"
  note "  dig TXT ${CHALLENGE_FQDN}"
fi
# ──────────────────────────────────────────────────────────────────────────

finish